function circuitTM(VDD,RG1,RG2,RD,RS,A,F,N,Vp,Id,Va,B,RL)

% ========== mesaje erori ===================%
if RG1<0||RG2<0||RD<0||RS<0
    f = errordlg('Rezistenta negativa? Impresionant.','Error');
end
if RG1==0||RG2==0||RD==0||RS==0
    f = errordlg('Rezistenta zero!','Error');
end
if F<0
    f = errordlg('Frecventa negativa?','Error');
elseif F>2600
    f = errordlg('Frecventa este prea mare!','Error');
end

% ========== figura interfata ===================%
Fig=figure('Name','TEC-MOS',...
'Units','normalized',...
'NumberTitle','off',...
'Position',[0.16 0.1 0.7 0.7],...
'Color','#F0F0F0');

% ========== semnal mic ===================%
uicontrol('Style','pushbutton',... % buton program
 'Units','normalized',...
 'Position',[0.05 0.58 0.08 0.025],...
 'string','fig. semnal mic',...
 'Callback','semnalmic()');

% ========== formule ===================%
T=(1/F); % perioada
t=(0:T/100:N*T); % timp in funct de nr de perioade N

Vi=A.*sin(2.*pi.*F.*t); % tensiunea de intrare vi

for i=1:length(t)
    if Vi(i) > VDD
        Vi(i) = VDD
    elseif Vi(i) < -VDD
        Vi(i) = -VDD
    end
end

VGS=(sqrt((Id/B)+Vp)); % tensiunea de iesire vo (AC)
gm=(2*B*(VGS-Vp));
rds=(Va/Id);
aa=((RD*rds)/(RD+rds));
bb=((aa*RL)/(aa+RL));
if RL==0
    Av=(gm*aa);
else
    Av=(gm*bb);
end
Vo=(Av*Vi);

VD=(VDD-(Id*RD)); % tensiunea de iesire VO (AC DC)
VO=(VD+Vo);

% ========== buton calcul ===================%
uicontrol('Style','pushbutton',...
 'Units','normalized',...
 'Position',[0.4 0.58 0.08 .04],...
 'string','CALCULEAZA',...
 'Callback','close,circuitTM(VDD,RG1,RG2,RD,RS,A,F,N,Vp,Id,Va,B,RL)')

% ========== imagine ===================%
img = imread('TM.png');
image(img);
x = 0.05;
y = 0.65;
width = 0.3; % measured relative to the figure width
height = 0.3; % measured relative to the figure height
set(gca,'units','normalized','position',[x y width height])
axis off;

% ========== grup1 butoane ===================%
RadioGroup=uibuttongroup('Visible','on',...
'ForegroundColor','black',...
'Title','‎‎‏‏‎‏‏‎ ‎‎‎‏‏‎',...
'FontSize',15,...
'TitlePosition','centertop',...
'Tag','radiobutton',...
'Position',[0.4 0.65 0.18 0.3]);

% ========== RG1 ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.80 0.3 0.1],...
'foregroundcolor','black',...
'String','RG1 [kOhm]',...
'Parent',RadioGroup);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.82 0.3 0.1],...
 'String',RG1,...
 'Parent',RadioGroup,...
 'Callback',['RG1=','str2num(get(gco,''String''))']);

% ========== RG2 ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.6 0.3 0.1],...
'foregroundcolor','black',...
'String','RG2 [kOhm]',...
'Parent',RadioGroup);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.62 0.3 0.1],...
 'String',RG2,...
 'Parent',RadioGroup,...
 'Callback',['RG2=','str2num(get(gco,''String''))']);

% ========== RD ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.4 0.3 0.1],...
'foregroundcolor','black',...
'String','RD [kOhm]',...
'Parent',RadioGroup);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.42 0.3 0.1],...
 'String',RD,...
 'Parent',RadioGroup,...
 'Callback',['RD=','str2num(get(gco,''String''))']);

% ========== RS ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.2 0.3 0.1],...
'foregroundcolor','black',...
'String','RS [kOhm]',...
'Parent',RadioGroup);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.22 0.3 0.1],...
 'String',RS,...
 'Parent',RadioGroup,...
 'Callback',['RS=','str2num(get(gco,''String''))']);

% ========== RL ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.0 0.3 0.1],...
'foregroundcolor','black',...
'String','RL [kOhm]',...
'Parent',RadioGroup);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.02 0.3 0.1],...
 'String',RL,...
 'Parent',RadioGroup,...
 'Callback',['RL=','str2num(get(gco,''String''))']);

% ========== grup2 butoane ===================%
RadioGroup2=uibuttongroup('Visible','on',...
'ForegroundColor','black',...
'Title','‎‎‏‏‎‏‏‎ ‎‎',...
'FontSize',15,...
'TitlePosition','centertop',...
'Tag','radiobutton',...
'Position',[0.56 0.65 0.18 0.3]);

% ========== VDD ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.80 0.3 0.1],...
'foregroundcolor','black',...
'String','VDD [V]',...
'Parent',RadioGroup2);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.82 0.3 0.1],...
 'String',VDD,...
 'Parent',RadioGroup2,...
 'Callback',['VDD=','str2num(get(gco,''String''))']);

% ========== A ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.6 0.3 0.1],...
'foregroundcolor','black',...
'String','A [V]',...
'Parent',RadioGroup2);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.62 0.3 0.1],...
 'String',A,...
 'Parent',RadioGroup2,...
 'Callback',['A=','str2num(get(gco,''String''))']);

% ========== Vp ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.4 0.3 0.1],...
'foregroundcolor','black',...
'String','Vp [V]',...
'Parent',RadioGroup2);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.42 0.3 0.1],...
 'String',Vp,...
 'Parent',RadioGroup2,...
 'Callback',['Vp=','str2num(get(gco,''String''))']);

% ========== Va ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.2 0.3 0.1],...
'foregroundcolor','black',...
'String','Va [V]',...
'Parent',RadioGroup2);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.22 0.3 0.1],...
 'String',Va,...
 'Parent',RadioGroup2,...
 'Callback',['Va=','str2num(get(gco,''String''))']);

% ========== grup3 butoane ===================%
RadioGroup2=uibuttongroup('Visible','on',...
'ForegroundColor','black',...
'Title','‎‎‏‏‎‏‏‎ ‎‎',...
'FontSize',15,...
'TitlePosition','centertop',...
'Tag','radiobutton',...
'Position',[0.72 0.65 0.18 0.3]);

% ========== B ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.8 0.3 0.1],...
'foregroundcolor','black',...
'String','B [A / V^2]',...
'Parent',RadioGroup2);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.82 0.3 0.1],...
 'String',B,...
 'Parent',RadioGroup2,...
 'Callback',['B=','str2num(get(gco,''String''))']);

% ========== F ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.6 0.3 0.1],...
'foregroundcolor','black',...
'String','F [Hz]',...
'Parent',RadioGroup2);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.62 0.3 0.1],...
 'String',F,...
 'Parent',RadioGroup2,...
 'Callback',['F=','str2num(get(gco,''String''))']);

% ========== Id ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.4 0.3 0.1],...
'foregroundcolor','black',...
'String','Id [A]',...
'Parent',RadioGroup2);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.42 0.3 0.1],...
 'String',Id,...
 'Parent',RadioGroup2,...
 'Callback',['Id=','str2num(get(gco,''String''))']);

% ========== N ===================%
uicontrol('Style','text',... % text
'Units','normalized',...
'Position',[0.03 0.2 0.3 0.1],...
'foregroundcolor','black',...
'String','N',...
'Parent',RadioGroup2);
uicontrol('Style','edit',... % edit
 'Units','normalized',...
 'Position',[0.45 0.22 0.3 0.1],...
 'String',N,...
 'Parent',RadioGroup2,...
 'Callback',['N=','str2num(get(gco,''String''))']);

% ========== Ri, Ro ===================%
Ri=((RG1*RG2)/(RG1+RG2));
Ro=((rds*RD)/(rds+RD));
uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.6 0.56 0.06 .04],...
          'FontSize',15,...
          'foregroundcolor','black',...
          'String','Ri =');
uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.64 0.56 0.06 .04],...
          'FontSize',15,...
          'String',Ri);
uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.74 0.56 0.06 .04],...
          'FontSize',15,...
          'foregroundcolor','black',...
          'String','Ro =');
uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.78 0.56 0.06 .04],...
          'FontSize',15,...
          'String',Ro);

% ========== gf tens.in Vi; tens.out vo(AC) ===================%
subplot('position',[0.05 0.2 0.25 0.25]);
plot(t,Vi,'LineWidth', 2, 'Color','#000000');
grid on;
title('Vi & vo');
xlabel('Timp [ms]');
ylabel('Amplitudine [V]');
hold on
plot(t,Vo,'LineWidth', 2, 'Color','#FF0000');
plot(t,Vo,'LineWidth', 2, 'Color','r');
legend('Vi','vo')
hold off

% ========== gf tens.out. vG ===================%
subplot('position',[0.38 0.2 0.25 0.25]);
plot(t,Vi,'LineWidth', 2, 'Color','#000000');
grid on;
title('vG');
xlabel('Timp [ms]');
ylabel('Amplitudine [V]');

% ========== gf tens.out VO(AC DC) ===================%
subplot('position',[0.71 0.2 0.25 0.25]);
plot(t,VO,'LineWidth', 2, 'Color','#0000FF');
grid on;
title('VO');
xlabel('Timp [ms]');
ylabel('Amplitudine [V]');
